name: Github Page
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: npm
      - run: npm i
      - run: npx ng build
      - run: mv dist/fuse docs
      - run: |
          git config --global user.name Ethereal
          git config --global user.email ethereal97@gmail.com
          git checkout gh-pages
          git add .
          git commit -m 'Github Page'
          git push origin gh-pages --force

