name: Github Page
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install —-global @angular/cli
      - run: npm install
      - run: npm build
      - run: mv dist docs
      - run: git checkout -B gh-pages
      - run: git add .
      - run: git commit -m 'Github Page'
      - run: git push origin gh-pages
