name: Github Page
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm i
      - run: npx ng build
      - run: mv dist docs
      - run: |
          git config --global user.name Ethereal
          git config --global user.email ethereal97@gmail.com
      - run: git checkout -B gh-pages
      - run: git add .
      - run: git commit -m 'Github Page'
      - run: git push origin gh-pages
